local M = {}

M.icons = {
  diagnostics = {
    Error = ' ',
    Warn  = ' ',
    Hint  = '󰌶 ',
    Info  = ' ',
  },
  git = {
    added    = ' ',
    modified = ' ',
    removed  = ' ',
  },
  kind = {
    Array         = '󰅪 ',
    Boolean       = ' ',
    Calendar      = ' ',
    Class         = '󰠱 ',
    Color         = '󰏘 ',
    Constant      = '󰏿 ',
    Constructor   = ' ',
    Enum          = ' ',
    EnumMember    = ' ',
    Event         = ' ',
    Field         = '󰜢 ',
    File          = '󰈙 ',
    Folder        = '󰉋 ',
    Function      = '󰊕 ',
    Interface     = ' ',
    Keyword       = '󰌋 ',
    Method        = '󰆧 ',
    Module        = ' ',
    Namespace     = '󰌗 ',
    Null          = '󰟢 ',
    Number        = ' ',
    Object        = '󰅩 ',
    Operator      = '󰆕 ',
    Package       = ' ',
    Property      = '󰜢 ',
    Reference     = '󰈇 ',
    Snippet       = ' ',
    String        = '󰉿 ',
    Struct        = '󰙅 ',
    Table         = ' ',
    Tag           = ' ',
    Text          = '󰉿 ',
    TypeParameter = '󰊄 ',
    Unit          = '󰑭 ',
    Value         = '󰎠 ',
    Variable      = '󰀫 ',
    Watch         = '󰥔 ',
  },
}

return M
